const express=require('express');const cors=require('cors');const webpush=require('web-push');const WebSocket=require('ws');const crypto=require('crypto');
const app=express();app.use(cors());app.use(express.json({limit:'32kb'}));const subs=new Map();
if(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY)webpush.setVapidDetails(process.env.VAPID_SUBJECT||'mailto:teste@vagasio.com.br',process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);
app.get('/health',(q,r)=>r.json({ok:true,video:true,signaling:'json-relay-v2',rooms:rooms.size}));app.get('/public-key',(q,r)=>r.json({publicKey:process.env.VAPID_PUBLIC_KEY||null}));
app.post('/subscribe',(q,r)=>{const s=q.body;if(!s?.endpoint||!s?.keys?.p256dh||!s?.keys?.auth)return r.status(400).json({erro:'Assinatura inválida'});subs.set(s.endpoint,s);r.json({ok:true})});
app.post('/send-test',async(q,r)=>{if(!process.env.VAPID_PUBLIC_KEY||!process.env.VAPID_PRIVATE_KEY)return r.status(503).json({erro:'VAPID não configurado'});let n=0;for(const[e,s]of subs)try{await webpush.sendNotification(s,JSON.stringify({title:'VagasIO — teste real',body:'Notificação enviada pelo backend de teste.'}));n++}catch(x){if(x.statusCode===404||x.statusCode===410)subs.delete(e)}r.json({ok:true,enviados:n})});
const TTL=15*60*1000,rooms=new Map();function makeRoom(){const room='entrevista-'+crypto.randomBytes(4).toString('hex');const item={room,tokens:{recrutador:crypto.randomBytes(24).toString('hex'),candidato:crypto.randomBytes(24).toString('hex')},expiresAt:Date.now()+TTL,ended:false,peers:new Map()};rooms.set(room,item);return item}
app.post('/create-room',(q,r)=>{const x=makeRoom(),base='https://sistemarecrutsmento.github.io/vagas-push-teste/video.html';const url=(role,name)=>base+'?room='+encodeURIComponent(x.room)+'&token='+x.tokens[role]+'&role='+role+'&nome='+encodeURIComponent(String(name||role).slice(0,80));r.json({ok:true,room:x.room,recrutador_url:url('recrutador',q.body?.recrutador||'Recrutador'),candidato_url:url('candidato',q.body?.candidato||'Candidato'),expira_em:new Date(x.expiresAt).toISOString()})});
const send=(s,m)=>{if(s?.readyState===WebSocket.OPEN)s.send(JSON.stringify(m))};const relay=(x,m,except)=>x.peers.forEach(s=>{if(s!==except)send(s,m)});const deny=(s,type,reason)=>{send(s,{type,reason});setTimeout(()=>s.close(1008,reason),30)};
const server=app.listen(process.env.PORT||3000,()=>console.log('isolated video signaling v2 online'));const wss=new WebSocket.Server({server});
wss.on('connection',s=>{let x=null,role=null,joined=false;s.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch(e){return send(s,{type:'error',code:'invalid-json'})}if(m.type==='join'){if(joined)return deny(s,'unauthorized','join-once');const r=String(m.role||'').toLowerCase(),room=rooms.get(String(m.room||'').slice(0,80));if(!room)return deny(s,'unauthorized','unknown-room');if(room.ended)return deny(s,'ended','room-ended');if(Date.now()>=room.expiresAt)return deny(s,'expired','room-expired');if(!['recrutador','candidato'].includes(r)||m.token!==room.tokens[r])return deny(s,'unauthorized','invalid-role-token');if(room.peers.has(r)||room.peers.size>=2)return deny(s,'full',room.peers.has(r)?'role-already-connected':'room-full');x=room;role=r;joined=true;s.info={nome:String(m.nome||'Participante').slice(0,80),perfil:r};x.peers.set(r,s);send(s,{type:'joined',role:r,expiresAt:x.expiresAt});const other=[...x.peers.entries()].find(([k])=>k!==r);if(!other)send(s,{type:'waiting'});else{send(s,{type:'peer-info',...other[1].info});send(other[1],{type:'peer-info',...s.info});const recruiter=role==='recrutador'?s:other[1];send(recruiter,{type:'ready',offerer:'recrutador'});}return}if(!joined||!x)return;if(m.type==='end-call'){if(role!=='recrutador')return deny(s,'unauthorized','recruiter-only-end-call');if(x.ended)return; x.ended=true;relay(x,{type:'call-ended',by:'recrutador'});send(s,{type:'call-ended',by:'recrutador'});x.peers.forEach(p=>{try{p.close(1000,'call-ended')}catch(e){}});x.peers.clear();return}if(['offer','answer','candidate','chat'].includes(m.type))relay(x,m,s)});s.on('close',()=>{if(!x||!joined)return;if(x.peers.get(role)===s)x.peers.delete(role);if(!x.ended)relay(x,{type:'peer-left',role})})});
setInterval(()=>{const now=Date.now();for(const[id,x]of rooms)if(now>=x.expiresAt){relay(x,{type:'expired'});x.peers.forEach(p=>{try{p.close(1000,'expired')}catch(e){}});rooms.delete(id)}},30000).unref();
